# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
+The data for this report can be found at https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip.  
+After downloading the data set, it is read into R to analyze it.
+
+``` {r}
+dat <- read.csv("activity.csv")
+```



## What is mean total number of steps taken per day?
+Here is a histogram showing the frequencies of the individual's number of steps per day.  Entries of "NA" are ignored.  
+``` {r}
+clean <- na.omit(dat) 
+days <- unique(clean$date)
+daily <- c()
+for (i in 1:length(days)) {
+        daily <- append(daily,sum(subset(clean, clean$date == days[i])$steps))
+}
+hist(daily)
+```

+The **mean** and **median** total number of steps taken per day can be calculated by looking at the daily totals tallied in the *daily* variable above.  Again, entries of "NA" are ignored.


## What is the average daily activity pattern?
+``` {r}
+stepsMean <- mean(daily)
+stepsMedian <- median(daily)
+stepsMean
+stepsMedian
+```
+So on days when data was collected, the individual in this case took an average of 10,766 steps per day with a median value of 10.765 steps.

+## What is the average daily activity pattern?
+``` {r}
+# there are 12*24 5 min intervals in a day, plot them using avg data across all days
+```



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
